version: "2"
services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017/tcp
    networks:
      mongo_net:
        ipv4_address: 0.0.0.0
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
  # redis:
  #   image: 'bitnami/redis:latest'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
  # rabbit:
  #   image: rabbitmq:3-management
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - '8080:15672'
  #     - '5672:5672'
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=password
  # postgresql:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #   ports:
  #     - '5432:5432'
