version: '2'
services:
  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017/tcp
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
