version: '2'
services:
  # mongo:
  #   image: mongo:4.2
  #   ports:
  #     - 27017:27017/tcp
  # redis:
  #   image: 'bitnami/redis:latest'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
  # rabbit:
  #   image: rabbitmq:3-management
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - '8080:15672'
  #     - '5672:5672'
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=password
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
