version: "2"
services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017/tcp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=insight
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
  # redis:
  #   image: 'bitnami/redis:latest'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
  # rabbit:
  #   image: rabbitmq:3-management
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - '8080:15672'
  #     - '5672:5672'
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=password
  # db:
  #   image: postgres:12
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   volumes:
  #     - ../db:/var/lib/postgresql/data
  #     - ./postgresql.conf:/etc/postgresql/postgresql.conf
  #   ports:
  #     - 5432:5432
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
